### ISSUE TITLE
smbclient code breaks moving from 0.1.6 to 0.2.0

### ISSUE THREAD

**Issue by ShlomoAbraham** [jborean93/pyspnego#22]
Hello,

I have the following code that used to work with pyspnego 0.1.6, but now fails with pyspnego 0.2.0, with your package smbprotocol:

```
import smbclient
smbclient.ClientConfig(domain_controller='dc01.mycompany.net', auth='kerberos')
```

Kerberos ticket is previously initialized with kinit.

**Comment by ShlomoAbraham** [comment]
Here's the logs I have:

INFO:smbprotocol.connection:Initialising connection, guid: 46e65430-1d91-4a9b-8614-95c6d63978f2, require_signing: True, server_name: dc01.mycompany.net, port: 445 
INFO:smbprotocol.connection:Setting up transport connection 
INFO:smbprotocol.transport:Connecting to DirectTcp socket 
INFO:smbprotocol.connection:Starting negotiation with SMB server 
INFO:smbprotocol.connection:Negotiating with SMB2 protocol with highest client dialect of: SMB_3_1_1 
INFO:smbprotocol.connection:Sending SMB2 Negotiate message 
INFO:smbprotocol.connection:Receiving SMB2 Negotiate response 
INFO:smbprotocol.connection:Negotiated dialect: (770) SMB_3_0_2 
INFO:smbprotocol.connection:Connection require signing: True 
INFO:smbprotocol.session:Initialising session with username: None 
INFO:__main__:sleeping for 600 seconds 
INFO:smbprotocol.transport:Disconnecting DirectTcp socket 
Traceback (most recent call last): 
File \"/opt/conda/lib/python3.9/site-packages/smbprotocol/session.py\", line 275, in connect 
out_token = context.step(in_token) 
File \"/opt/conda/lib/python3.9/site-packages/spnego/_negotiate.py\", line 112, in step 
mech_token_in, mech_list_mic, is_spnego = self._step_spnego_input(in_token=in_token) 
File \"/opt/conda/lib/python3.9/site-packages/spnego/_negotiate.py\", line 156, in _step_spnego_input 
mech_list = self._rebuild_context_list(mech_types=in_token.mech_types) 
File \"/opt/conda/lib/python3.9/site-packages/spnego/_negotiate.py\", line 396, in _rebuild_context_list 
raise BadMechanismError(context_msg=\"Unable to negotiate common mechanism\", base_error=last_err) 
spnego.exceptions.BadMechanismError: SpnegoError (1): SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath, Context: Unable to negotiate common mechanism 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File \"//src/myscript.py\", line 1995, in <module> 
parse_file_function() 
File \"/opt/conda/lib/python3.9/site-packages/reporting_common/utils/derf_attribute.py\", line 29, in __call__ 
to_return = self.func(*args, **kwargs) 
File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 1137, in __call__ 
return self.main(*args, **kwargs) 
File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 1062, in main 
rv = self.invoke(ctx) 
File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 1404, in invoke 
return ctx.invoke(self.callback, **ctx.params) 
File \"/opt/conda/lib/python3.9/site-packages/click/core.py\", line 763, in invoke 
return __callback(*args, **kwargs) 
File \"//src/myscript.py\", line 1658, in parse_file_function 
smbclient.ClientConfig(domain_controller='dc01.mycompany.net', auth='kerberos') 
File \"/opt/conda/lib/python3.9/site-packages/smbclient/_pool.py\", line 67, in __call__ 
config.domain_controller = dc_value 
File \"/opt/conda/lib/python3.9/site-packages/smbclient/_pool.py\", line 129, in domain_controller 
ipc_tree = get_smb_tree(u'\\\\\\\\%s\\\\IPC$' % value)[0] 
File \"/opt/conda/lib/python3.9/site-packages/smbclient/_pool.py\", line 299, in get_smb_tree 
session = register_session(server, username=username, password=password, port=port, encrypt=encrypt, 
File \"/opt/conda/lib/python3.9/site-packages/smbclient/_pool.py\", line 367, in register_session 
session.connect() 
File \"/opt/conda/lib/python3.9/site-packages/smbprotocol/session.py\", line 277, in connect 
raise SMBAuthenticationError(\"Failed to authenticate with server: %s\" % str(err.message)) 
smbprotocol.exceptions.SMBAuthenticationError: Failed to authenticate with server: SpnegoError (1): SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath, Context: Unable to negotiate common mechanism 
INFO:smbprotocol.connection:Disconnecting transport connection

**Comment by jborean93** [comment]
There's a good chance you may need to install [krb5](https://pypi.org/project/krb5/) as without it pyspnego will consider Kerberos unavailable https://github.com/jborean93/pyspnego/blob/6a9eea4ab1a039bf57dc2761564ef995251a142e/spnego/_gss.py#L30-L39. This requirement was added to [pyspnego's requirements](https://github.com/jborean93/pyspnego/blob/6a9eea4ab1a039bf57dc2761564ef995251a142e/setup.py#L81-L84) but unfortunately I believe smbprotocol still only has gssapi.
