### ISSUE TITLE
python-gssapi minimum requirement needs to be bumped

### ISSUE THREAD

**Issue by lfortemps** [jborean93/pyspnego#43]
Hi,
Thanks for the great libraries!
I have noticed you make use of the 'dotted_form' for the oids. However it looks like this property is not defined on python-gssapi 1.5.1 for instance (default in RHEL 8 repository at this time)
The requirements specificy gssapi>1.5.0. 

I think you would need to bump that requirement.

Cheers

**Comment by jborean93** [comment]
Thanks for the pickup, I see it was added in 1.6.0 with https://github.com/pythongssapi/python-gssapi/commit/96fb80b1f02724cb5716c6e7863f15490d69e0a1. Do you know if RHEL 8 is planning on updating the versions at some point? If not I might try and find a workaround if possible to ensure it will still work on that older platform.
