### ISSUE TITLE
Deprecation warning in tls.py

### ISSUE THREAD

**Issue by Shnitzelil** [jborean93/pyspnego#78]
Hi,

A deprecation warning raised on tls.py line 129 datetime.datetime.utcnow().
this should be replaced with datetime.datetime.now(datetime.timezone.utc)

Thanks

**Comment by jborean93** [comment]
Thanks for letting me know, the PR https://github.com/jborean93/pyspnego/pull/79 moves to the recommended syntax.

**Comment by Shnitzelil** [comment]
> Thanks for letting me know, the PR #79 moves to the recommended syntax.

Thank you for the quick response.
Will you release new package?

**Comment by jborean93** [comment]
I will push it through at some point soon.
